# Node.js v22.16.0 Alpine pinned by digest (architecture: linux/amd64) for immutability
# podman manifest inspect docker.io/library/node:22-alpine
FROM node@sha256:11d923cca2138d844282dc0c333132bba72deb913d635c3c33e54523b455a4da

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "start"]